---
ingress:
  enabled: true
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
  tls:
    - secretName: jellyfin-tls
      hosts:
        - jellyfin.homelab.luisbrancher.dev
  hosts:
    - host: jellyfin.homelab.luisbrancher.dev
      paths:
        - path: /
          pathType: Prefix

service:
  main:
    type: NodePort
    ports:
      http:
        port: 8096
        nodePort: 30096

persistence:
  config:
    enabled: true
    existingClaim: jellyfin-config-pvc
  media:
    enabled: true
    existingClaim: jellyfin-media-pvc

securityContext:
  runAsUser: 0
  runAsGroup: 0
