---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nextcloud-pv
spec:
  capacity:
    storage: 1500Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  nfs:
    server: 10.10.10.15
    path: /mnt/data-ssd/nextcloud
  persistentVolumeReclaimPolicy: Retain
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nextcloud-pvc
  namespace: nextcloud
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  resources:
    requests:
      storage: 1500Gi
  volumeName: nextcloud-pv