---
image:
  repository: nextcloud
  tag: 31.0.14
  
# Ajuste de recursos para garantir estabilidade durante a migração
resources:
  requests:
    cpu: 250m
    memory: 512Mi
  limits:
    memory: 1Gi

nextcloud:
  host: nextcloud.homelab.luisbrancher.dev
  existingSecret:
    enabled: true
    secretName: nextcloud-credentials
    usernameKey: username
    passwordKey: password

ingress:
  enabled: true
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
  tls:
    - secretName: nextcloud-tls
      hosts:
        - nextcloud.homelab.luisbrancher.dev
  hosts:
    - host: nextcloud.homelab.luisbrancher.dev
      paths:
        - path: /
          pathType: Prefix

persistence:
  enabled: true
  existingClaim: nextcloud-pvc

internalDatabase:
  enabled: false

postgresql:
  enabled: false

externalDatabase:
  enabled: true
  type: postgresql
  host: nextcloud-postgresql
  database: nextcloud
  existingSecret:
    enabled: true
    secretName: nextcloud-db-credentials
    usernameKey: username
    passwordKey: password

livenessProbe:
  initialDelaySeconds: 120
  periodSeconds: 30
  failureThreshold: 10

readinessProbe:
  initialDelaySeconds: 120
  periodSeconds: 30
  failureThreshold: 10