---
nextcloud:
  host: nextcloud.homelab.luisbrancher.dev
  existingSecret:
    enabled: true
    secretName: nextcloud-credentials
    usernameKey: username
    passwordKey: password

ingress:
  enabled: true
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
  tls:
    - secretName: nextcloud-tls
      hosts:
        - nextcloud.homelab.luisbrancher.dev
  hosts:
    - host: nextcloud.homelab.luisbrancher.dev
      paths:
        - path: /
          pathType: Prefix

persistence:
  enabled: true
  existingClaim: nextcloud-pvc

internalDatabase:
  enabled: false

postgresql:
  enabled: true
  image:
    tag: 16-debian-12   # tag flutuante, sempre existe
  global:
    postgresql:
      auth:
        existingSecret: nextcloud-db-credentials