---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: immich-pv
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  nfs:
    server: 10.10.10.15
    path: /mnt/data-ssd/immich
  persistentVolumeReclaimPolicy: Retain
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-pvc
  namespace: immich
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  resources:
    requests:
      storage: 200Gi
  volumeName: immich-pv
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: immich-nextcloud-photos-pv
spec:
  capacity:
    storage: 200Gi
  accessModes:
    - ReadOnlyMany
  storageClassName: ""
  nfs:
    server: 10.10.10.15         
    path: /mnt/data-ssd/nextcloud/photos
  persistentVolumeReclaimPolicy: Retain
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-nextcloud-photos-pvc
  namespace: immich
spec:
  accessModes:
    - ReadOnlyMany
  storageClassName: ""
  resources:
    requests:
      storage: 200Gi
  volumeName: immich-nextcloud-photos-pv