---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: immich-pv
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    server: 192.168.1.x
    path: /mnt/data/immich
  persistentVolumeReclaimPolicy: Retain
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-pvc
  namespace: immich
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
  volumeName: immich-pv


---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: immich-nextcloud-photos-pv
spec:
  capacity:
    storage: 200Gi
  accessModes:
    - ReadOnlyMany       # ← read-only
  nfs:
    server: 192.168.1.x
    path: /mnt/data/nextcloud/photos   # mesmo path do Nextcloud
  persistentVolumeReclaimPolicy: Retain
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-nextcloud-photos-pvc
  namespace: immich
spec:
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 200Gi
  volumeName: immich-nextcloud-photos-pv