x-immich-version: &immich-version "v3.0.3"

controllers:
  main:
    containers:
      main:
        image:
          repository: ghcr.io/immich-app/immich-server
          tag: *immich-version
        env:
          DB_HOSTNAME: immich-postgres-rw
          DB_USERNAME:
            valueFrom:
              secretKeyRef:
                name: immich-postgres-credentials
                key: username
          DB_PASSWORD:
            valueFrom:
              secretKeyRef:
                name: immich-postgres-credentials
                key: password
          DB_DATABASE_NAME: immich
          REDIS_HOSTNAME: immich-valkey
          IMMICH_MACHINE_LEARNING_URL: http://immich-machine-learning:3003

# Configuração exclusiva do painel web
server:
  image:
    tag: *immich-version
  # O Ingress agora vive AQUI DENTRO, só para o server
  ingress:
    main:
      enabled: true
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
      tls:
        - secretName: immich-tls
          hosts:
            - immich.homelab.luisbrancher.dev
      hosts:
        - host: immich.homelab.luisbrancher.dev
          paths:
            - path: /
              pathType: Prefix

machine-learning:
  image:
    tag: *immich-version

valkey:
  enabled: true

extraVolumes:
  - name: nextcloud-photos
    persistentVolumeClaim:
      claimName: immich-nextcloud-photos-pvc
      readOnly: true

extraVolumeMounts:
  - name: nextcloud-photos
    mountPath: /usr/src/app/external
    readOnly: true

immich:
  persistence:
    library:
      existingClaim: immich-pvc

podSecurityContext:
  runAsUser: 0
  runAsGroup: 0
  fsGroup: 0