---
image:
  tag: v3.0.0

env:
  DB_HOSTNAME: immich-postgres-rw
  DB_USERNAME:
    valueFrom:
      secretKeyRef:
        name: immich-postgres-credentials
        key: username
  DB_PASSWORD:
    valueFrom:
      secretKeyRef:
        name: immich-postgres-credentials
        key: password
  DB_DATABASE_NAME: immich
  REDIS_HOSTNAME: immich-valkey
  IMMICH_MACHINE_LEARNING_URL: http://immich-machine-learning:3003

immich:
  persistence:
    library:
      existingClaim: immich-pvc

valkey:
  enabled: true

ingress:
  server:
    enabled: true
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
    tls:
      - secretName: immich-tls
        hosts:
          - immich.homelab.luisbrancher.dev
    hosts:
      - host: immich.homelab.luisbrancher.dev
        paths:
          - path: /
            pathType: Prefix